### PR TITLE
Convert GNU regex to POSIX regex

### PR DESCRIPTION
**Pull request by alarixnia**
Needed by future NetBSD releases.

### CODE REVIEW

**Comment by rmottola** [comment]
Can you explain me this a little better? I did not have issues on NetBSD 9.99 currenlty

**Comment by alarixnia** [comment]
In 20210223 new regular expression code was added which disables GNU syntax lile \S by default unless configured to allow it. [:space:] is standardised so should work everywhere.

**Comment by rmottola** [comment]
@alarixnia I pushed this in the dev branch, if you want to try, I will probably merge into master soon. Let me know.

**Comment by rmottola** [comment]
it should be in, even if it appears not here.
Fine for you?

**Pull request closed without merging**
